### ISSUE TITLE
Вопрос о справедливости

### ISSUE THREAD

**Issue by bzaar** [sokirko74/aot#12]
Как указано на сайте [aot.ru](http://aot.ru/docs/rusmorph.html),

> Русский морфологический словарь Диалинг базируется на грамматическом словаре А.А.Зализняка[1987].

Т.е. в основе этого открытого репозитория лежит 13-летний кропотливый труд выдающегося лингвиста.

@sokirko74 Алексей, вопрос лично к вам. Считаете ли вы себя вправе распоряжаться плодами чужого труда – выкладывать их в открытый доступ или, наоборот, ограничивать доступ к ним лицензиями? По российским законам исключительное право на произведение охраняется в течение 70 лет с года, следующего за годом смерти автора (ст. 1281 ГК РФ). Но я спрашиваю не с целью проверить вашу юридическую подкованность. Мой вопрос адресован вашему чувству справедливости.

**Comment by sokirko74** [comment]
Мне кажется,  словарь Зализняка был  важен своим метаописанием (предисловием), которым, конечно, все пользуются, это часть общего знания.  «Величие» словаря Зализняка именно в его предисловии.   Сам словарь включал 100К слов, словарь aot.ru включает сейчас 298301 слов (в три раза больше). Это разные словари, у нас гораздо больше ошибок:)  Если говорить о финансовой стороне дела, то оцифрованная версия словаря Зализняка была куплена у академического института со всеми правами коммерческого и некоммерческого использования.  Я не хочу раскрывать все подробности этой сделки, но она была добровольной:)  Дальше мне, как соучредителю юридического лица,  купившего этот словарь, была предоставлена возможность опубликовать этот словарь, я это сделал. С моей точки зрения, после возникновения Wiktionary  значимость словаря aot.ru  резко снизилась, иногда я даже не понимаю, что мы тут обсуждаем.  Короче, с моей точки зрения, все справедливо.

**Comment by bzaar** [comment]
Алексей, спасибо за ответ! Возможно, я сейчас открою для вас что-то новое в этом вопросе двадцатилетней давности.

В [предисловии](https://gramdict.ru/preface) к четвертому изданию (2003 г.) автор упоминает преинтересный эпизод:

> Работа [над словарем] делалась вне каких бы то ни было планов Академии наук, и именно это позволило словарю выйти в свет, причем в том виде, который соответствовал замыслам автора: тогдашний директор Института русского языка АН СССР Ф. П. Филин требовал от издательства «Русский язык» снять словарь с производства, но издательство, которое в ведомственном отношении было независимо от Академии наук, ему не подчинилось.

Раз Академия наук требовала снять словарь с производства, значит, у нее не было планов выпускать такой словарь, что подтверждает слова Андрея Анатольевича, что над словарем он работал не как сотрудник АН, а самостоятельно, как частное лицо. Впрочем, я и без лишних подтверждений ему верю. Все, что он говорил, до сих пор оказывалось правдой :)

Таким образом, права на словарь изначально принадлежали автору, а Академии наук никогда не принадлежали.

Как по-вашему, имел «академический институт» право продавать не свой словарь?

Я никого не обвиняю, просто призываю разобраться в этом вопросе.

**Comment by sokirko74** [comment]
1. Если хочется разбираться, разбирайтесь. Абстрактная справедливость мне не очень интересна.  Должно быть ущемление прав конкретных людей.  Когда-то был словарь Зализняка на 100К, сейчас есть Wiktionary, который закрывает 80% всего Зализняка(по моим прикидкам), остальные 20% вообще по вопросом, поскольку в словаре Зализняка много устаревших слов.  В словаре  aot.ru  еще добавлены 200К.  Нам придется доказывать, что aot.ru минус весь Wiktionary и минус  все добавленные нами слова вредят Анне Зализняк.  
2. Нарушение издательством требования правообладателя не означает, что у последнего теряется право на словарь.
3.  Интуиция мне подсказывает, что вы беспокоитесь совсем не о наследниках Зализняка, а о себе.

**Comment by bzaar** [comment]
Я считаю, что имеет место ущемление прав конкретного человека - автора «Грамматического словаря». В российских и международных законах есть такое право - «право автора на имя». В лицензиях Creative Commons оно именуется -BA-, Attribution. Оно обязывает авторов производных работ указывать, на чем их работы основаны. Так, например, в браузере Google Chrome есть [список](chrome://credits/) всех использованных в нем модулей с открытым исходным кодом. 

Я считаю, что «Грамматический словарь» незаслуженно забыт. Растворился в «Поиске» Яндекса, спеллчекере Микрософта и тысячах других программ и сервисов, создатели которых не посчитали нужным даже упомянуть имя автора словаря, не то что спросить его разрешения использовать словарь в коммерческих продуктах.

Как минимум, мы должны Зализняку его право на имя.

Например, сборник словарей hunspell имеет отдельный [файл](https://github.com/wooorm/dictionaries/blob/main/dictionaries/ru/license) с лицензией на морфологический словарь, где четко указано имя автора - Alexander I. Lebedev, а в [readme](https://github.com/wooorm/dictionaries/blob/main/dictionaries/ru/readme.md) указана ссылка на [источник](https://code.google.com/archive/p/hunspell-ru/).

Предлагаю в readme данного репозитория указать, что словарь АОТ основан на словаре Зализняка. Если хотите, могу сделать PR.

**Comment by sokirko74** [comment]
1. На  aot.ru  есть ссылка на словарь Зализняка. 
2. Посещаемость aot.ru - 10 человек в день. 
3. С этого репозитория есть ссылка на aot.ru.
4. В этом репозитории нет словаря, он находится в другом моем репозитории.  Чтобы попытаться остановить это обсуждение, я сейчас добавил ссылку  в readme.md [этого другого репозитория](https://github.com/sokirko74/morph_dict) .  Куда еще добавить?  
5. Вы серьезно говорите о PR Зализняка с помощью таких действий?

**Comment by bzaar** [comment]
Под PR я имел в виду pull request :) Извините, думал, что на Гитхабе эта аббревиатура понимается однозначно. Спасибо за README. 

> оцифрованная версия словаря Зализняка была куплена у академического института со всеми правами коммерческого и некоммерческого использования. Я не хочу раскрывать все подробности этой сделки, но она была добровольной:) 

А можете раскрыть хотя бы стороны сделки?

**Comment by sokirko74** [comment]
Стороны сделки, деньги и дату раскрою на суде.  Документ сохранился.
